<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
      <_Parameter1>MyOS.Tests</_Parameter1>
    </AssemblyAttribute>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
      <_Parameter1>MyOS.UnitTests</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="MediatR" Version="14.1.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.7" />
    <PackageReference Include="SqlKata.Execution" Version="2.4.0" />
  </ItemGroup>
	
  <ItemGroup>
    <ProjectReference Include="..\MyOS.Core.Domain\MyOS.Core.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Resources\PagingErrors_en.resx" />
    <EmbeddedResource Update="Resources\PagingErrors_pl.resx" />
  </ItemGroup>

</Project>
