<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
      <_Parameter1>MyOS.Tests</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MyOS.Core.Application\MyOS.Core.Application.csproj" />
    <ProjectReference Include="..\MyOS.Identity.Domain\MyOS.Identity.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="10.0.7" />
  </ItemGroup>


</Project>
