<Project Sdk="Microsoft.NET.Sdk.Web">
	<PropertyGroup>
		<UserSecretsId>94a2dda8-d836-47cb-b72d-1e1e592e83a6</UserSecretsId>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Asp.Versioning.Mvc" Version="8.1.0" />
		<PackageReference Include="Asp.Versioning.Mvc.ApiExplorer" Version="8.1.0" />
		<PackageReference Include="DotNetEnv" Version="3.2.0" />
		<PackageReference Include="Swashbuckle.AspNetCore" Version="6.9.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\MyOS.Core.Infrastructure\MyOS.Core.Infrastructure.csproj" />
		<ProjectReference Include="..\MyOS.Identity.Infrastructure\MyOS.Identity.Infrastructure.csproj" />
		<ProjectReference Include="..\MyOS.Modules.Notes.Infrastructure\MyOS.Modules.Notes.Infrastructure.csproj" />
			<ProjectReference Include="..\MyOS.Modules.Storage.Infrastructure\MyOS.Modules.Storage.Infrastructure.csproj" />
	</ItemGroup>

</Project>
