<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\MyOS.Core.Infrastructure\MyOS.Core.Infrastructure.csproj" />
    <ProjectReference Include="..\MyOS.Identity.Application\MyOS.Identity.Application.csproj" />
    <ProjectReference Include="..\MyOS.Identity.Domain\MyOS.Identity.Domain.csproj" />
  </ItemGroup>

</Project>
